export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_START = 'ADD_USER_START';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';
export const ADD_DESTINATION_SUCCESS = 'ADD_DESTINATION_SUCCESS';
export const GET_DESTINATIONS_SUCCESS = 'GET_DESTINATIONS_SUCCESS';
