export const ADD_DESTINATION_SUCCESS = 'ADD_DESTINATION_SUCCESS';
export const GET_DESTINATIONS_SUCCESS = 'GET_DESTINATIONS_SUCCESS';

export const GET_TRIPS_REQUEST_START = 'GET_TRIPS_REQUEST_START';
export const GET_TRIPS_REQUEST_SUCCESS = 'GET_TRIPS_REQUEST_SUCCESS';
export const GET_TRIPS_REQUEST_FAILURE = 'GET_TRIPS_REQUEST_FAILURE';

export const PUT_TRIP_REQUEST_START = 'PUT_TRIP_REQUEST_START';
export const PUT_TRIP_REQUEST_SUCCESS = 'PUT_TRIP_REQUEST_SUCCESS';
export const PUT_TRIP_REQUEST_FAILURE = 'PUT_TRIP_REQUEST_FAILURE';
