// Trips
export const GET_TRIPS_REQUEST = 'GET_TRIPS_REQUEST';
export const GET_TRIPS_SUCCESS = 'GET_TRIPS_SUCCESS';
export const GET_TRIPS_FAILURE = 'GET_TRIPS_FAILURE';

export const PUT_TRIP_REQUEST = 'PUT_TRIP_REQUEST';
export const PUT_TRIP_SUCCESS = 'PUT_TRIP_SUCCESS';
export const PUT_TRIP_FAILURE = 'PUT_TRIP_FAILURE';

export const POST_TRIP_REQUEST = 'POST_TRIP_REQUEST';
export const POST_TRIP_SUCCESS = 'POST_TRIP_SUCCESS';
export const POST_TRIP_FAILURE = 'POST_TRIP_FAILURE';

export const GET_TRIPS_FOR_USER_REQUEST = 'GET_TRIPS_FOR_USER_REQUEST';
export const GET_TRIPS_FOR_USER_SUCCESS = 'GET_TRIPS_FOR_USER_SUCCESS';
export const GET_TRIPS_FOR_USER_FAILURE = 'GET_TRIPS_FOR_USER_FAILURE';

export const GET_TRIPS_FOR_DESTINATION_REQUEST = 'GET_TRIPS_FOR_DESTINATION_REQUEST';
export const GET_TRIPS_FOR_DESTINATION_SUCCESS = 'GET_TRIPS_FOR_DESTINATION_SUCCESS';
export const GET_TRIPS_FOR_DESTINATION_FAILURE = 'GET_TRIPS_FOR_DESTINATION_FAILURE';
