export const GET_ADMIN_VALUES_REQUEST = 'GET_ADMIN_VALUES_REQUEST';
export const GET_ADMIN_VALUES_SUCCESS = 'GET_ADMIN_VALUES_SUCCESS';
export const GET_ADMIN_VALUES_FAILURE = 'GET_ADMIN_VALUES_FAILURE';

export const GET_ADMIN_VALUE_REQUEST = 'GET_ADMIN_VALUE_REQUEST';
export const GET_ADMIN_VALUE_SUCCESS = 'GET_ADMIN_VALUE_SUCCESS';
export const GET_ADMIN_VALUE_FAILURE = 'GET_ADMIN_VALUE_FAILURE';

export const POST_ADMIN_VALUE_REQUEST = 'POST_ADMIN_VALUE_REQUEST';
export const POST_ADMIN_VALUE_SUCCESS = 'POST_ADMIN_VALUE_SUCCESS';
export const POST_ADMIN_VALUE_FAILURE = 'POST_ADMIN_VALUE_FAILURE';

export const PUT_ADMIN_VALUE_REQUEST = 'PUT_ADMIN_VALUE_REQUEST';
export const PUT_ADMIN_VALUE_SUCCESS = 'PUT_ADMIN_VALUE_SUCCESS';
export const PUT_ADMIN_VALUE_FAILURE = 'PUT_ADMIN_VALUE_FAILURE';
