export const POST_DESTINATION_REQUEST = 'POST_DESTINATION_REQUEST';
export const POST_DESTINATION_SUCCESS = 'POST_DESTINATION_SUCCESS';
export const POST_DESTINATION_FAILURE = 'POST_DESTINATION_FAILURE';

export const GET_DESTINATIONS_REQUEST = 'GET_DESTINATIONS_REQUEST';
export const GET_DESTINATIONS_SUCCESS = 'GET_DESTINATIONS_SUCCESS';
export const GET_DESTINATIONS_FAILURE = 'GET_DESTINATIONS_FAILURE';

export const GET_DESTINATION_REQUEST = 'GET_DESTINATION_REQUEST';
export const GET_DESTINATION_SUCCESS = 'GET_DESTINATION_SUCCESS';
export const GET_DESTINATION_FAILURE = 'GET_DESTINATION_FAILURE';
