export const GET_EMAIL_REQUEST = 'GET_EMAIL_REQUEST';
export const GET_EMAIL_SUCCESS = 'GET_EMAIL_SUCCESS';
export const GET_EMAIL_FAILURE = 'GET_EMAIL_FAILURE';

export const PUT_EMAIL_REQUEST = 'PUT_EMAIL_REQUEST';
export const PUT_EMAIL_SUCCESS = 'PUT_EMAIL_SUCCESS';
export const PUT_EMAIL_FAILURE = 'PUT_EMAIL_FAILURE';
